// marketsui-fi-ng/src/app/components/fi-trading/positions-panel/positions-panel.component.ts
import {
  Component,
  ViewEncapsulation,
  ChangeDetectionStrategy,
  signal,
  computed,
  inject,
} from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { HlmButtonDirective } from '../../../shared/ui/hlm-button.directive';
import { AllEnterpriseModule, ModuleRegistry } from 'ag-grid-enterprise';
import type { ColDef, GridReadyEvent, RowClickedEvent } from 'ag-grid-community';
import { HighchartsChartComponent } from 'highcharts-angular';
import type { Options, AxisLabelsFormatterContextObject } from 'highcharts';
import { MarketDataService } from '../../../services/market-data.service';
import { Position, AssetClass } from '../../../models/market-data.models';
import { marketsUITheme } from '../../../shared/ag-grid-theme';
import { fmtPnL, fmtDV01, fmtPrice, fmtYield } from '../../../shared/utils';

ModuleRegistry.registerModules([AllEnterpriseModule]);

type AssetFilter = 'All' | AssetClass;
const ASSET_FILTERS: AssetFilter[] = ['All', 'Treasury', 'Corporate', 'Future', 'CDS'];

const CLASS_COLORS: Record<string, string> = {
  Treasury: 'text-primary', Corporate: 'text-buy', Future: 'text-warning', CDS: 'text-sell',
};

@Component({
  selector: 'app-positions-panel',
  standalone: true,
  imports: [AgGridAngular, HighchartsChartComponent, HlmButtonDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="h-full flex flex-col overflow-hidden p-3 space-y-3">
      <!-- KPI Row -->
      <div class="grid grid-cols-6 gap-2 shrink-0">
        @for (kpi of kpis(); track kpi.label) {
          <div class="bg-card border border-border rounded-xl px-4 py-3 flex flex-col gap-0.5">
            <span class="text-[10px] text-muted-foreground uppercase tracking-widest">{{ kpi.label }}</span>
            <span class="text-xl font-semibold font-mono leading-tight mt-0.5" [class]="kpi.cls">{{ kpi.value }}</span>
            @if (kpi.sub) {
              <span class="text-[10px] text-muted-foreground mt-0.5">{{ kpi.sub }}</span>
            }
          </div>
        }
      </div>

      <!-- Grid + Sidebar -->
      <div class="flex-1 min-h-0 grid grid-cols-12 gap-3">
        <!-- Positions Grid -->
        <div class="col-span-9 flex flex-col overflow-hidden">
          <!-- Filter buttons -->
          <div class="flex items-center justify-between mb-2 shrink-0">
            <div class="flex items-center gap-1">
              @for (f of assetFilters; track f) {
                <button
                  hlmBtn
                  [variant]="assetFilter() === f ? 'default' : 'ghost'"
                  size="sm"
                  (click)="assetFilter.set(f)"
                  class="rounded-full text-[10px] h-6 px-2"
                >
                  {{ f }}
                </button>
              }
            </div>
            <span class="text-[11px] text-muted-foreground">{{ rowData().length }} positions</span>
          </div>

          <!-- AG Grid -->
          <div class="flex-1 min-h-0">
            <ag-grid-angular
              style="width: 100%; height: 100%;"
              [theme]="theme"
              [rowData]="rowData()"
              [columnDefs]="colDefs"
              [defaultColDef]="defaultColDef"
              [rowHeight]="40"
              [headerHeight]="30"
              [rowSelection]="rowSelection"
              [pinnedBottomRowData]="pinnedBottomRowData()"
              [suppressCellFocus]="true"
              [enableCellTextSelection]="true"
              (rowClicked)="onRowClicked($event)"
              (gridReady)="onGridReady($event)"
            />
          </div>
        </div>

        <!-- Right sidebar -->
        <div class="col-span-3 flex flex-col gap-3 overflow-hidden">
          <!-- DV01 by Class Chart -->
          <div class="bg-card border border-border rounded-xl overflow-hidden flex flex-col" style="height: 220px;">
            <div class="px-4 py-2.5 border-b border-border shrink-0">
              <span class="text-xs font-semibold">DV01 by Class</span>
            </div>
            <div class="flex-1 p-2 min-h-0">
              <highcharts-chart
                [options]="dv01ClassChartOptions"
                style="width:100%;height:100%;display:block;"
              />
            </div>
          </div>

          <!-- Detail / Attribution -->
          @if (selected(); as sel) {
            <div class="flex-1 bg-card border border-border rounded-xl overflow-hidden flex flex-col min-h-0">
              <div class="px-4 py-3 border-b border-border shrink-0">
                <div class="font-semibold text-sm">{{ sel.security }}</div>
                <div class="text-[10px] text-muted-foreground font-mono mt-0.5">{{ sel.cusip }}</div>
              </div>
              <div class="mx-3 mt-3 px-3 py-2.5 rounded-lg shrink-0"
                [class.bg-buy/10]="sel.pnlToday >= 0"
                [class.bg-sell/10]="sel.pnlToday < 0"
              >
                <div class="text-[10px] text-muted-foreground uppercase tracking-wider mb-0.5">P&L Today</div>
                <div class="text-xl font-semibold font-mono"
                  [class.text-buy]="sel.pnlToday >= 0"
                  [class.text-sell]="sel.pnlToday < 0"
                >{{ formatPnL(sel.pnlToday) }}</div>
              </div>
              <div class="flex-1 overflow-y-auto px-3 py-3">
                <div class="grid grid-cols-2 gap-x-2 gap-y-3 text-[11px]">
                  @for (item of getDetailItems(sel); track item.label) {
                    <div>
                      <div class="text-[9px] text-muted-foreground uppercase tracking-wide mb-0.5">{{ item.label }}</div>
                      <div class="font-mono font-medium">{{ item.value }}</div>
                    </div>
                  }
                </div>
              </div>
            </div>
          } @else {
            <div class="flex-1 bg-card border border-border rounded-xl overflow-hidden flex flex-col min-h-0">
              <div class="px-4 py-2.5 border-b border-border shrink-0">
                <span class="text-xs font-semibold">P&L Attribution</span>
              </div>
              <div class="flex-1 overflow-y-auto divide-y divide-border">
                @for (p of sortedByPnl; track p.id) {
                  <div class="flex items-center justify-between px-4 py-2 text-[11px]">
                    <span class="text-muted-foreground truncate mr-2">{{ p.security }}</span>
                    <div class="flex items-center gap-2 shrink-0">
                      <div class="w-12 h-1 bg-secondary rounded-full overflow-hidden">
                        <div
                          class="h-full rounded-full"
                          [class.bg-buy]="p.pnlToday >= 0"
                          [class.bg-sell]="p.pnlToday < 0"
                          [style.width.%]="pnlBarWidth(p.pnlToday)"
                        ></div>
                      </div>
                      <span class="font-mono font-semibold w-16 text-right"
                        [class.text-buy]="p.pnlToday >= 0"
                        [class.text-sell]="p.pnlToday < 0"
                      >{{ formatPnL(p.pnlToday) }}</span>
                    </div>
                  </div>
                }
              </div>
            </div>
          }
        </div>
      </div>
    </div>
  `,
})
export class PositionsPanelComponent {
  private readonly marketDataService = inject(MarketDataService);

  readonly theme = marketsUITheme;
  readonly assetFilters = ASSET_FILTERS;
  readonly assetFilter = signal<AssetFilter>('All');
  readonly selected = signal<Position | null>(null);
  readonly formatPnL = fmtPnL;
  readonly formatDV01 = fmtDV01;

  readonly rowSelection: any = { mode: 'singleRow', checkboxes: false, enableClickSelection: true };

  private get allPositions(): readonly Position[] {
    return this.marketDataService.positions;
  }

  readonly totalPnlToday = computed(() => this.allPositions.reduce((s, p) => s + p.pnlToday, 0));
  readonly totalPnlMtd   = computed(() => this.allPositions.reduce((s, p) => s + p.pnlMtd, 0));
  readonly totalPnlYtd   = computed(() => this.allPositions.reduce((s, p) => s + p.pnlYtd, 0));
  readonly totalDV01     = computed(() => this.allPositions.reduce((s, p) => s + p.dv01, 0));
  readonly totalCS01     = computed(() => this.allPositions.reduce((s, p) => s + p.cs01, 0));
  readonly totalMktVal   = computed(() => this.allPositions.filter(p => p.mktVal !== 0).reduce((s, p) => s + p.mktVal, 0));

  readonly kpis = computed(() => {
    const pnlToday = this.totalPnlToday();
    const pnlMtd = this.totalPnlMtd();
    const pnlYtd = this.totalPnlYtd();
    return [
      { label: 'P&L Today',    value: fmtPnL(pnlToday),                           cls: pnlToday >= 0 ? 'text-buy' : 'text-sell', sub: '' },
      { label: 'P&L MTD',      value: fmtPnL(pnlMtd),                              cls: pnlMtd >= 0 ? 'text-buy' : 'text-sell',   sub: '' },
      { label: 'P&L YTD',      value: fmtPnL(pnlYtd),                              cls: pnlYtd >= 0 ? 'text-buy' : 'text-sell',   sub: '' },
      { label: 'Net DV01',     value: fmtDV01(this.totalDV01()),                    cls: '',                                        sub: 'Rate sensitivity' },
      { label: 'Net CS01',     value: fmtDV01(this.totalCS01()),                    cls: '',                                        sub: 'Credit sensitivity' },
      { label: 'Market Value', value: '$' + this.totalMktVal().toFixed(1) + 'MM',   cls: '',                                        sub: 'Long positions' },
    ];
  });

  readonly rowData = computed(() => {
    const filter = this.assetFilter();
    return filter === 'All' ? [...this.allPositions] : this.allPositions.filter(p => p.assetClass === filter);
  });

  readonly pinnedBottomRowData = computed(() => [{
    id: 'total', security: 'TOTAL', cusip: '', assetClass: '' as any, side: '' as any,
    size: 0, avgPx: 0, currPx: 0, currYld: 0,
    dv01: this.totalDV01(), cs01: this.totalCS01(),
    pnlToday: this.totalPnlToday(), pnlMtd: this.totalPnlMtd(), pnlYtd: this.totalPnlYtd(),
    mktVal: 0,
  } as Position]);

  get sortedByPnl(): readonly Position[] {
    return [...this.allPositions].sort((a, b) => Math.abs(b.pnlToday) - Math.abs(a.pnlToday));
  }

  readonly colDefs: ColDef<Position>[] = [
    {
      field: 'security', headerName: 'Security', width: 160, pinned: 'left',
      cellRenderer: (p: any) => `<div class="flex flex-col justify-center h-full leading-none gap-0.5">
        <div class="font-semibold text-[11px]">${p.data?.security ?? ''}</div>
        <div class="text-[10px] text-muted-foreground font-mono">${p.data?.cusip ?? ''}</div>
      </div>`,
      filter: 'agTextColumnFilter',
    },
    {
      field: 'assetClass', headerName: 'Class', width: 82,
      cellRenderer: (p: any) => {
        const cls = CLASS_COLORS[p.value] ?? 'text-muted-foreground';
        return `<span class="text-[10px] font-medium ${cls}">${p.value ?? ''}</span>`;
      },
      filter: 'agSetColumnFilter',
    },
    {
      field: 'side', headerName: 'Side', width: 78,
      cellRenderer: (p: any) => {
        const isLong = p.value === 'LONG';
        return `<span class="text-[10px] px-2 py-0.5 rounded-full font-semibold tracking-wide ${isLong ? 'bg-buy/15 text-buy' : 'bg-sell/15 text-sell'}">${p.value ?? ''}</span>`;
      },
      filter: 'agSetColumnFilter',
    },
    {
      field: 'size', headerName: 'Size', width: 78, type: 'rightAligned',
      cellClass: 'font-mono font-semibold',
      valueFormatter: p => p.data?.assetClass === 'Future' ? `${p.value} cts` : `$${p.value}MM`,
    },
    {
      field: 'avgPx', headerName: 'Avg Px', width: 72, type: 'rightAligned',
      cellClass: 'font-mono text-muted-foreground',
      valueFormatter: p => fmtPrice(p.value),
    },
    {
      field: 'currPx', headerName: 'Curr Px', width: 72, type: 'rightAligned',
      cellClass: 'font-mono',
      valueFormatter: p => fmtPrice(p.value),
    },
    {
      field: 'currYld', headerName: 'Curr Yld', width: 76, type: 'rightAligned',
      cellClass: 'font-mono text-muted-foreground',
      valueFormatter: p => p.value > 0 ? fmtYield(p.value) : '\u2014',
    },
    {
      field: 'dv01', headerName: 'DV01', width: 76, type: 'rightAligned',
      cellClass: 'font-mono',
      valueFormatter: p => fmtDV01(p.value),
      cellStyle: p => ({ color: (p.value ?? 0) >= 0 ? 'inherit' : 'var(--sell)' }),
    },
    {
      field: 'cs01', headerName: 'CS01', width: 72, type: 'rightAligned',
      cellClass: 'font-mono text-muted-foreground',
      valueFormatter: p => p.value > 0 ? fmtDV01(p.value) : '\u2014',
    },
    {
      field: 'pnlToday', headerName: 'P&L Today', width: 90, type: 'rightAligned',
      cellRenderer: (p: any) => `<span class="font-mono font-semibold ${(p.value ?? 0) >= 0 ? 'text-buy' : 'text-sell'}">${fmtPnL(p.value ?? 0)}</span>`,
      filter: 'agNumberColumnFilter',
    },
    {
      field: 'pnlMtd', headerName: 'P&L MTD', width: 88, type: 'rightAligned',
      cellRenderer: (p: any) => `<span class="font-mono ${(p.value ?? 0) >= 0 ? 'text-buy' : 'text-sell'}">${fmtPnL(p.value ?? 0)}</span>`,
      filter: 'agNumberColumnFilter',
    },
    {
      field: 'pnlYtd', headerName: 'P&L YTD', width: 88, type: 'rightAligned',
      cellRenderer: (p: any) => `<span class="font-mono ${(p.value ?? 0) >= 0 ? 'text-buy' : 'text-sell'}">${fmtPnL(p.value ?? 0)}</span>`,
      filter: 'agNumberColumnFilter',
    },
  ];

  readonly defaultColDef: ColDef = {
    sortable: true,
    resizable: true,
    minWidth: 50,
  };

  pnlBarWidth(pnl: number): number {
    return Math.min(Math.abs(pnl) / 45000 * 100, 100);
  }

  getDetailItems(sel: Position): { label: string; value: string }[] {
    return [
      { label: 'Side',    value: sel.side },
      { label: 'Class',   value: sel.assetClass },
      { label: 'Size',    value: sel.assetClass === 'Future' ? `${sel.size} cts` : `$${sel.size}MM` },
      { label: 'Avg Px',  value: fmtPrice(sel.avgPx) },
      { label: 'Curr Px', value: fmtPrice(sel.currPx) },
      { label: 'Yield',   value: sel.currYld > 0 ? fmtYield(sel.currYld) : '\u2014' },
      { label: 'DV01',    value: fmtDV01(sel.dv01) },
      { label: 'CS01',    value: sel.cs01 > 0 ? fmtDV01(sel.cs01) : '\u2014' },
      { label: 'MTD',     value: fmtPnL(sel.pnlMtd) },
      { label: 'YTD',     value: fmtPnL(sel.pnlYtd) },
    ];
  }

  onRowClicked(e: RowClickedEvent<Position>): void {
    const curr = this.selected();
    if (curr?.id === e.data?.id) {
      this.selected.set(null);
    } else {
      this.selected.set(e.data ?? null);
    }
  }

  onGridReady(e: GridReadyEvent): void {
    e.api.sizeColumnsToFit();
  }

  /* ── Highcharts DV01 by Class (horizontal bar) ──────────── */
  readonly dv01ClassChartOptions: Options = (() => {
    const positions = this.marketDataService.positions;
    const dv01ByClass = [
      { label: 'Treasury',  dv01: positions.filter(p => p.assetClass === 'Treasury').reduce((s, p) => s + p.dv01, 0) },
      { label: 'Corporate', dv01: positions.filter(p => p.assetClass === 'Corporate').reduce((s, p) => s + p.dv01, 0) },
      { label: 'Futures',   dv01: positions.filter(p => p.assetClass === 'Future').reduce((s, p) => s + p.dv01, 0) },
      { label: 'CDS',       dv01: positions.filter(p => p.assetClass === 'CDS').reduce((s, p) => s + p.dv01, 0) },
    ];

    const classColors = ['#60A5FA', '#0D9488', '#5B93D5', '#E11D63'];
    const borderColor = '#2C2F33';
    const mutedFg = '#9DA0A5';

    return {
      chart: { type: 'bar', backgroundColor: 'transparent', style: { fontFamily: "'Inter', sans-serif" } },
      credits: { enabled: false },
      title: { text: undefined },
      legend: { enabled: false },
      xAxis: {
        categories: dv01ByClass.map((d) => d.label),
        lineColor: borderColor,
        tickColor: borderColor,
        labels: { style: { color: mutedFg, fontSize: '10px' } },
        gridLineWidth: 0,
      },
      yAxis: {
        title: { text: undefined },
        gridLineColor: borderColor + '66',
        gridLineWidth: 0.5,
        labels: {
          style: { color: mutedFg, fontSize: '9px' },
          formatter(this: AxisLabelsFormatterContextObject): string {
            return typeof this.value === 'number' ? '$' + (this.value / 1000).toFixed(0) + 'K' : String(this.value);
          },
        },
      },
      tooltip: {
        backgroundColor: 'rgba(26, 29, 33, 0.95)',
        borderColor: borderColor,
        style: { color: '#FFFFFF', fontSize: '10px' },
        formatter(this: any): string {
          return `<b>${this.x}</b><br/>DV01: $${Math.abs(this.y ?? 0).toLocaleString()}`;
        },
      },
      plotOptions: {
        bar: {
          pointPadding: 0.15,
          groupPadding: 0.1,
          borderWidth: 0,
          borderRadius: 3,
        },
        series: { animation: false },
      },
      series: [{
        type: 'bar' as const,
        name: 'DV01',
        data: dv01ByClass.map((d, i) => ({
          y: d.dv01,
          color: classColors[i] + 'B3',
        })),
      }],
    };
  })();
}

// marketsui-fi/src/components/trading/fi/PositionsPanel.tsx
import { useState, useMemo, useCallback } from 'react'
import type { ReactNode } from 'react'
import type { ColDef, ICellRendererParams, RowClassParams } from 'ag-grid-community'
import { AgGridReact } from 'ag-grid-react'
import { AllEnterpriseModule } from 'ag-grid-enterprise'
import Highcharts from 'highcharts'
import { HighchartsReact } from 'highcharts-react-official'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { marketsUITheme } from './agGridTheme'
import { PanelGrid, DragHandle } from './PanelGrid'
import { BASE_POSITIONS, fmtPnL, fmtK } from './marketData'
import type { Position, AssetClass } from './marketData'

/* ── Constants ──────────────────────────────────────────── */

type FilterType = 'All' | AssetClass
const FILTERS: FilterType[] = ['All', 'Treasury', 'Corporate', 'Future', 'CDS']

const CLASS_COLOR: Record<AssetClass, string> = {
  Treasury: 'text-primary',
  Corporate: 'text-buy',
  Future: 'text-warning',
  CDS: 'text-sell',
}

const BAR_COLORS: Record<string, string> = {
  Treasury: 'var(--primary)',
  Corporate: 'var(--buy)',
  Future: 'var(--warning)',
  CDS: 'var(--sell)',
}

/* ── Helpers ────────────────────────────────────────────── */

function fmtPosSize(pos: Position) {
  if (pos.assetClass === 'Future') return `${pos.size} cts`
  return `$${pos.size}MM`
}

function fmtMktVal(n: number) {
  const abs = Math.abs(n)
  if (abs >= 1_000_000_000) return (n / 1_000_000_000).toFixed(2) + 'B'
  if (abs >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M'
  return (n / 1_000).toFixed(0) + 'K'
}

/* ── Cell Renderers ─────────────────────────────────────── */

function SecurityRenderer(params: ICellRendererParams<Position>) {
  const d = params.data
  if (!d) return null
  return (
    <div className="flex flex-col leading-tight py-1">
      <span className="text-[11px] font-medium text-foreground truncate">{d.security}</span>
      <span className="text-[9px] text-muted-foreground font-mono">{d.cusip}</span>
    </div>
  )
}

function ClassRenderer(params: ICellRendererParams<Position>) {
  const d = params.data
  if (!d) return null
  return (
    <span className={cn('text-[10px] font-semibold uppercase', CLASS_COLOR[d.assetClass])}>
      {d.assetClass}
    </span>
  )
}

function PosSideRenderer(params: ICellRendererParams<Position>) {
  const d = params.data
  if (!d) return null
  const isLong = d.side === 'LONG'
  return (
    <span
      className={cn(
        'inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold',
        isLong ? 'bg-buy/10 text-buy' : 'bg-sell/10 text-sell'
      )}
    >
      {d.side}
    </span>
  )
}

function PnlCellRenderer(params: ICellRendererParams<Position>) {
  const val = params.value as number | undefined
  if (val == null) return null
  return (
    <span className={cn('font-mono text-[11px]', val >= 0 ? 'text-buy' : 'text-sell')}>
      {fmtPnL(val)}
    </span>
  )
}

/* ── KPI Card ───────────────────────────────────────────── */

function KpiCard({ label, value, colored }: { label: string; value: string; colored?: boolean }) {
  const isNeg = value.startsWith('-')
  return (
    <div className="bg-card border border-border rounded-xl p-3 flex flex-col gap-0.5">
      <span className="text-[10px] text-muted-foreground uppercase tracking-wider font-medium">{label}</span>
      <span
        className={cn(
          'text-base font-semibold font-mono',
          colored ? (isNeg ? 'text-sell' : 'text-buy') : 'text-foreground'
        )}
      >
        {value}
      </span>
    </div>
  )
}

/* ── P&L Attribution List ───────────────────────────────── */

function PnlAttribution({ positions }: { positions: Position[] }) {
  const sorted = useMemo(
    () => [...positions].sort((a, b) => Math.abs(b.pnlToday) - Math.abs(a.pnlToday)),
    [positions]
  )
  const maxPnl = useMemo(
    () => Math.max(...sorted.map((p) => Math.abs(p.pnlToday)), 1),
    [sorted]
  )
  return (
    <div className="flex flex-col gap-1.5">
      <span className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold mb-1">
        P&amp;L Attribution (Today)
      </span>
      {sorted.map((p) => {
        const pct = (Math.abs(p.pnlToday) / maxPnl) * 100
        const pos = p.pnlToday >= 0
        return (
          <div key={p.id} className="flex flex-col gap-0.5">
            <div className="flex items-center justify-between text-[10px]">
              <span className="text-foreground truncate font-medium">{p.security}</span>
              <span className={cn('font-mono', pos ? 'text-buy' : 'text-sell')}>
                {fmtPnL(p.pnlToday)}
              </span>
            </div>
            <div className="h-1.5 w-full bg-muted rounded-full overflow-hidden">
              <div
                className={cn('h-full rounded-full', pos ? 'bg-buy' : 'bg-sell')}
                style={{ width: `${pct}%` }}
              />
            </div>
          </div>
        )
      })}
    </div>
  )
}

/* ── Position Detail ────────────────────────────────────── */

function PositionDetail({ position }: { position: Position }) {
  const isProfit = position.pnlToday >= 0

  const rows: [string, ReactNode][] = [
    ['Side', <span key="s" className={position.side === 'LONG' ? 'text-buy' : 'text-sell'}>{position.side}</span>],
    ['Class', <span key="c" className={CLASS_COLOR[position.assetClass]}>{position.assetClass}</span>],
    ['Size', <span key="sz" className="font-mono">{fmtPosSize(position)}</span>],
    ['Avg Px', <span key="ap" className="font-mono">{position.avgPx.toFixed(3)}</span>],
    ['Curr Px', <span key="cp" className="font-mono">{position.currPx.toFixed(3)}</span>],
    ['Yield', <span key="y" className="font-mono">{position.currYld ? position.currYld.toFixed(3) + '%' : '\u2014'}</span>],
    ['DV01', <span key="d" className="font-mono">${fmtK(position.dv01)}</span>],
    ['CS01', <span key="cs" className="font-mono">${fmtK(position.cs01)}</span>],
    ['MTD', <span key="mtd" className={cn('font-mono', position.pnlMtd >= 0 ? 'text-buy' : 'text-sell')}>{fmtPnL(position.pnlMtd)}</span>],
    ['YTD', <span key="ytd" className={cn('font-mono', position.pnlYtd >= 0 ? 'text-buy' : 'text-sell')}>{fmtPnL(position.pnlYtd)}</span>],
  ]

  return (
    <div className="flex flex-col gap-3">
      <div className={cn('rounded-lg p-3 text-center', isProfit ? 'bg-buy/10' : 'bg-sell/10')}>
        <div className="text-[10px] text-muted-foreground uppercase tracking-wider mb-0.5">P&amp;L Today</div>
        <div className={cn('text-xl font-bold font-mono', isProfit ? 'text-buy' : 'text-sell')}>
          {fmtPnL(position.pnlToday)}
        </div>
      </div>
      <div className="grid grid-cols-2 gap-x-3 gap-y-2">
        {rows.map(([label, value]) => (
          <div key={label as string} className="flex flex-col gap-0.5">
            <span className="text-[9px] text-muted-foreground uppercase tracking-wider">{label}</span>
            <span className="text-[11px] text-foreground">{value}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

/* ── Layouts ────────────────────────────────────────────── */

const GRID_LAYOUTS = {
  lg: [
    { i: 'kpi', x: 0, y: 0, w: 12, h: 3 },
    { i: 'grid', x: 0, y: 3, w: 9, h: 16 },
    { i: 'dv01Chart', x: 9, y: 3, w: 3, h: 6 },
    { i: 'detail', x: 9, y: 9, w: 3, h: 10 },
  ],
  md: [
    { i: 'kpi', x: 0, y: 0, w: 12, h: 3 },
    { i: 'grid', x: 0, y: 3, w: 9, h: 16 },
    { i: 'dv01Chart', x: 9, y: 3, w: 3, h: 6 },
    { i: 'detail', x: 9, y: 9, w: 3, h: 10 },
  ],
  sm: [
    { i: 'kpi', x: 0, y: 0, w: 6, h: 4 },
    { i: 'grid', x: 0, y: 4, w: 6, h: 14 },
    { i: 'dv01Chart', x: 0, y: 18, w: 6, h: 6 },
    { i: 'detail', x: 0, y: 24, w: 6, h: 8 },
  ],
}

/* ── Main Component ─────────────────────────────────────── */

export function PositionsPanel() {
  const [filter, setFilter] = useState<FilterType>('All')
  const [selectedId, setSelectedId] = useState<string | null>(null)

  const filteredPositions = useMemo(
    () => (filter === 'All' ? BASE_POSITIONS : BASE_POSITIONS.filter((p) => p.assetClass === filter)),
    [filter]
  )

  const totals = useMemo(() => {
    let totalPnlToday = 0
    let totalPnlMtd = 0
    let totalPnlYtd = 0
    let totalDV01 = 0
    let totalCS01 = 0
    let totalMktVal = 0
    for (const p of BASE_POSITIONS) {
      totalPnlToday += p.pnlToday
      totalPnlMtd += p.pnlMtd
      totalPnlYtd += p.pnlYtd
      totalDV01 += p.dv01
      totalCS01 += p.cs01
      totalMktVal += p.mktVal
    }
    return { totalPnlToday, totalPnlMtd, totalPnlYtd, totalDV01, totalCS01, totalMktVal }
  }, [])

  const dv01ByClass = useMemo(() => {
    const map: Record<string, number> = {}
    for (const p of BASE_POSITIONS) {
      map[p.assetClass] = (map[p.assetClass] ?? 0) + p.dv01
    }
    return Object.entries(map).map(([name, dv01]) => ({ name, dv01 }))
  }, [])

  const dv01ChartOptions = useMemo<Highcharts.Options>(
    () => ({
      chart: { type: 'bar', backgroundColor: 'transparent', style: { fontFamily: "'Inter', sans-serif" }, height: null as unknown as number },
      credits: { enabled: false },
      title: { text: undefined },
      xAxis: {
        categories: dv01ByClass.map((d) => d.name),
        labels: { style: { color: '#FFFFFF', fontSize: '10px' } },
        lineWidth: 0,
        tickLength: 0,
      },
      yAxis: {
        title: { text: undefined },
        labels: { enabled: false },
        gridLineWidth: 0,
        lineWidth: 0,
      },
      legend: { enabled: false },
      tooltip: {
        backgroundColor: '#1A1D21',
        borderColor: '#2C2F33',
        borderRadius: 8,
        style: { color: '#FFFFFF', fontSize: '11px', fontFamily: "'Inter', sans-serif" },
        formatter: function (this: Highcharts.TooltipFormatterContextObject) {
          return `<span style="color:#9DA0A5;font-size:10px">${this.x}</span><br/>DV01: $${fmtK(Number(this.y))}`
        },
        useHTML: true,
      },
      plotOptions: {
        bar: {
          borderRadius: 4,
          borderWidth: 0,
          pointWidth: 16,
          animation: false,
        },
      },
      series: [
        {
          name: 'DV01',
          type: 'bar',
          data: dv01ByClass.map((d) => ({
            y: d.dv01,
            color: BAR_COLORS[d.name] ?? '#60A5FA',
          })),
        },
      ],
    }),
    [dv01ByClass]
  )

  const selectedPosition = useMemo(
    () => BASE_POSITIONS.find((p) => p.id === selectedId) ?? null,
    [selectedId]
  )

  const pinnedBottom = useMemo<Position[]>(
    () => [
      {
        id: 'TOTAL',
        security: 'TOTAL',
        cusip: '',
        assetClass: '' as AssetClass,
        side: '' as 'LONG',
        size: 0,
        avgPx: 0,
        currPx: 0,
        currYld: 0,
        dv01: totals.totalDV01,
        cs01: totals.totalCS01,
        pnlToday: totals.totalPnlToday,
        pnlMtd: totals.totalPnlMtd,
        pnlYtd: totals.totalPnlYtd,
        mktVal: totals.totalMktVal,
      },
    ],
    [totals]
  )

  const columnDefs = useMemo<ColDef<Position>[]>(
    () => [
      {
        headerName: 'Security',
        field: 'security',
        width: 160,
        pinned: 'left' as const,
        cellRenderer: SecurityRenderer,
        suppressMovable: true,
      },
      {
        headerName: 'Class',
        field: 'assetClass',
        width: 82,
        cellRenderer: ClassRenderer,
      },
      {
        headerName: 'Side',
        field: 'side',
        width: 78,
        cellRenderer: PosSideRenderer,
      },
      {
        headerName: 'Size',
        field: 'size',
        width: 78,
        type: 'rightAligned',
        cellClass: 'font-mono',
        valueFormatter: (p) => (p.data ? fmtPosSize(p.data) : ''),
      },
      {
        headerName: 'Avg Px',
        field: 'avgPx',
        width: 72,
        type: 'rightAligned',
        cellClass: 'font-mono',
        valueFormatter: (p) => (p.value ? (p.value as number).toFixed(3) : ''),
      },
      {
        headerName: 'Curr Px',
        field: 'currPx',
        width: 72,
        type: 'rightAligned',
        cellClass: 'font-mono',
        valueFormatter: (p) => (p.value ? (p.value as number).toFixed(3) : ''),
      },
      {
        headerName: 'Curr Yld',
        field: 'currYld',
        width: 76,
        type: 'rightAligned',
        cellClass: 'font-mono',
        valueFormatter: (p) => (p.value ? (p.value as number).toFixed(3) + '%' : ''),
      },
      {
        headerName: 'DV01',
        field: 'dv01',
        width: 76,
        type: 'rightAligned',
        cellClass: 'font-mono',
        valueFormatter: (p) => (p.value != null ? '$' + Math.abs(p.value as number).toLocaleString() : ''),
      },
      {
        headerName: 'CS01',
        field: 'cs01',
        width: 72,
        type: 'rightAligned',
        cellClass: 'font-mono',
        valueFormatter: (p) => (p.value != null ? '$' + Math.abs(p.value as number).toLocaleString() : ''),
      },
      {
        headerName: 'P&L Today',
        field: 'pnlToday',
        width: 90,
        type: 'rightAligned',
        cellRenderer: PnlCellRenderer,
      },
      {
        headerName: 'P&L MTD',
        field: 'pnlMtd',
        width: 88,
        type: 'rightAligned',
        cellRenderer: PnlCellRenderer,
      },
      {
        headerName: 'P&L YTD',
        field: 'pnlYtd',
        width: 88,
        type: 'rightAligned',
        cellRenderer: PnlCellRenderer,
      },
    ],
    []
  )

  const defaultColDef = useMemo<ColDef>(
    () => ({ sortable: true, resizable: true, suppressHeaderMenuButton: true }),
    []
  )

  const onRowClicked = useCallback(
    (e: { data: Position | undefined }) => {
      if (e.data && e.data.id !== 'TOTAL') setSelectedId(e.data.id)
    },
    []
  )

  const getRowClass = useCallback(
    (params: RowClassParams<Position>) =>
      params.data?.id === 'TOTAL' ? 'font-semibold' : undefined,
    []
  )

  return (
    <PanelGrid layouts={GRID_LAYOUTS}>
      {/* KPI Row */}
      <div key="kpi" className="relative">
        <DragHandle />
        <div className="grid grid-cols-6 gap-2 h-full">
          <KpiCard label="P&L Today" value={fmtPnL(totals.totalPnlToday)} colored />
          <KpiCard label="P&L MTD" value={fmtPnL(totals.totalPnlMtd)} colored />
          <KpiCard label="P&L YTD" value={fmtPnL(totals.totalPnlYtd)} colored />
          <KpiCard label="Net DV01" value={'$' + fmtK(totals.totalDV01)} />
          <KpiCard label="Net CS01" value={'$' + fmtK(totals.totalCS01)} />
          <KpiCard label="Market Value" value={'$' + fmtMktVal(totals.totalMktVal)} />
        </div>
      </div>

      {/* Positions Grid */}
      <div key="grid" className="bg-card border border-border rounded-xl flex flex-col overflow-hidden relative">
        <DragHandle />
        <div className="flex items-center justify-between px-3 py-2 border-b border-border">
          <span className="text-xs font-semibold text-foreground">Positions</span>
          <div className="flex items-center gap-1">
            {FILTERS.map((f) => (
              <Button
                key={f}
                onClick={() => setFilter(f)}
                variant={filter === f ? 'default' : 'secondary'}
                size="sm"
                className="rounded-full"
              >
                {f}
              </Button>
            ))}
          </div>
        </div>
        <div className="flex-1 min-h-0">
          <AgGridReact<Position>
            theme={marketsUITheme}
            modules={[AllEnterpriseModule]}
            rowData={filteredPositions}
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            pinnedBottomRowData={pinnedBottom}
            getRowId={(p) => p.data.id}
            onRowClicked={onRowClicked}
            getRowClass={getRowClass}
            rowSelection="single"
            suppressCellFocus
            animateRows={false}
            statusBar={{
              statusPanels: [
                { statusPanel: 'agTotalAndFilteredRowCountComponent', align: 'left' },
              ],
            }}
          />
        </div>
      </div>

      {/* DV01 by Class Chart */}
      <div key="dv01Chart" className="bg-card border border-border rounded-xl flex flex-col overflow-hidden relative">
        <DragHandle />
        <div className="px-3 py-2 border-b border-border">
          <span className="text-xs font-semibold text-foreground">DV01 by Class</span>
        </div>
        <div className="flex-1 min-h-0 p-2">
          <div style={{ width: '100%', height: '100%' }}>
            <HighchartsReact highcharts={Highcharts} options={dv01ChartOptions} containerProps={{ style: { width: '100%', height: '100%' } }} />
          </div>
        </div>
      </div>

      {/* Detail / Attribution Panel */}
      <div key="detail" className="bg-card border border-border rounded-xl flex flex-col overflow-hidden relative">
        <DragHandle />
        <div className="px-3 py-2 border-b border-border">
          <span className="text-xs font-semibold text-foreground">
            {selectedPosition ? selectedPosition.security : 'P&L Attribution'}
          </span>
        </div>
        <div className="flex-1 min-h-0 overflow-auto p-3">
          {selectedPosition ? (
            <PositionDetail position={selectedPosition} />
          ) : (
            <PnlAttribution positions={BASE_POSITIONS} />
          )}
        </div>
      </div>
    </PanelGrid>
  )
}

export default PositionsPanel
