// marketsui-fi/src/components/trading/fi/DesignSystemPanel.tsx
import React from "react";

interface ColorToken {
  token: string;
  tailwind: string;
  description: string;
}

interface ColorGroup {
  label: string;
  tokens: ColorToken[];
}

const colorGroups: ColorGroup[] = [
  {
    label: "Core Surfaces",
    tokens: [
      { token: "--background", tailwind: "bg-background", description: "Page / app background" },
      { token: "--foreground", tailwind: "text-foreground", description: "Primary text color" },
      { token: "--card", tailwind: "bg-card", description: "Card / panel background" },
      { token: "--card-foreground", tailwind: "text-card-foreground", description: "Text on cards" },
      { token: "--popover", tailwind: "bg-popover", description: "Popover / dropdown background" },
      { token: "--popover-foreground", tailwind: "text-popover-foreground", description: "Text inside popovers" },
    ],
  },
  {
    label: "Brand",
    tokens: [
      { token: "--primary", tailwind: "bg-primary", description: "Primary brand / interactive color" },
      { token: "--primary-foreground", tailwind: "text-primary-foreground", description: "Text on primary backgrounds" },
    ],
  },
  {
    label: "Neutral",
    tokens: [
      { token: "--secondary", tailwind: "bg-secondary", description: "Secondary surfaces" },
      { token: "--secondary-foreground", tailwind: "text-secondary-foreground", description: "Text on secondary" },
      { token: "--muted", tailwind: "bg-muted", description: "Muted / subtle backgrounds" },
      { token: "--muted-foreground", tailwind: "text-muted-foreground", description: "De-emphasized text" },
      { token: "--accent", tailwind: "bg-accent", description: "Accent highlights" },
      { token: "--accent-foreground", tailwind: "text-accent-foreground", description: "Text on accent" },
    ],
  },
  {
    label: "Semantic",
    tokens: [
      { token: "--destructive", tailwind: "bg-destructive", description: "Error / destructive actions" },
      { token: "--destructive-foreground", tailwind: "text-destructive-foreground", description: "Text on destructive" },
    ],
  },
  {
    label: "Chrome",
    tokens: [
      { token: "--border", tailwind: "border-border", description: "Borders and dividers" },
      { token: "--input", tailwind: "border-input", description: "Input field borders" },
      { token: "--ring", tailwind: "ring-ring", description: "Focus ring color" },
    ],
  },
  {
    label: "Trading: Buy/Sell",
    tokens: [
      { token: "--buy", tailwind: "bg-buy", description: "Buy action background" },
      { token: "--buy-foreground", tailwind: "text-buy-foreground", description: "Text on buy background" },
      { token: "--sell", tailwind: "bg-sell", description: "Sell action background" },
      { token: "--sell-foreground", tailwind: "text-sell-foreground", description: "Text on sell background" },
    ],
  },
  {
    label: "Trading: P&L",
    tokens: [
      { token: "--positive", tailwind: "text-positive", description: "Profit / positive change" },
      { token: "--negative", tailwind: "text-negative", description: "Loss / negative change" },
      { token: "--unchanged", tailwind: "text-unchanged", description: "Flat / no change" },
    ],
  },
  {
    label: "Trading: Order Status",
    tokens: [
      { token: "--status-filled", tailwind: "text-status-filled", description: "Fully filled orders" },
      { token: "--status-partial", tailwind: "text-status-partial", description: "Partially filled orders" },
      { token: "--status-working", tailwind: "text-status-working", description: "Working / open orders" },
      { token: "--status-cancelled", tailwind: "text-status-cancelled", description: "Cancelled orders" },
      { token: "--status-rejected", tailwind: "text-status-rejected", description: "Rejected orders" },
    ],
  },
  {
    label: "Alerts",
    tokens: [
      { token: "--warning", tailwind: "bg-warning", description: "Warning / caution state" },
      { token: "--warning-foreground", tailwind: "text-warning-foreground", description: "Text on warning" },
      { token: "--info", tailwind: "bg-info", description: "Informational state" },
      { token: "--info-foreground", tailwind: "text-info-foreground", description: "Text on info" },
      { token: "--success", tailwind: "bg-success", description: "Success state" },
      { token: "--success-foreground", tailwind: "text-success-foreground", description: "Text on success" },
    ],
  },
  {
    label: "Charts",
    tokens: [
      { token: "--chart-1", tailwind: "bg-chart-1", description: "Chart series 1 (blue)" },
      { token: "--chart-2", tailwind: "bg-chart-2", description: "Chart series 2 (green)" },
      { token: "--chart-3", tailwind: "bg-chart-3", description: "Chart series 3 (amber)" },
      { token: "--chart-4", tailwind: "bg-chart-4", description: "Chart series 4 (red)" },
      { token: "--chart-5", tailwind: "bg-chart-5", description: "Chart series 5 (purple)" },
    ],
  },
  {
    label: "UI",
    tokens: [
      { token: "--highlight", tailwind: "bg-highlight", description: "Row hover highlight" },
      { token: "--selection", tailwind: "bg-selection", description: "Selected row / item" },
      { token: "--ticker-bar", tailwind: "bg-ticker-bar", description: "Scrolling ticker bar background" },
      { token: "--ticker-bar-foreground", tailwind: "text-ticker-bar-foreground", description: "Ticker bar text" },
    ],
  },
  {
    label: "Sidebar",
    tokens: [
      { token: "--sidebar", tailwind: "bg-sidebar", description: "Sidebar background" },
      { token: "--sidebar-foreground", tailwind: "text-sidebar-foreground", description: "Sidebar text" },
      { token: "--sidebar-primary", tailwind: "bg-sidebar-primary", description: "Sidebar primary accent" },
      { token: "--sidebar-primary-foreground", tailwind: "text-sidebar-primary-foreground", description: "Text on sidebar primary" },
      { token: "--sidebar-accent", tailwind: "bg-sidebar-accent", description: "Sidebar accent background" },
      { token: "--sidebar-accent-foreground", tailwind: "text-sidebar-accent-foreground", description: "Text on sidebar accent" },
      { token: "--sidebar-border", tailwind: "border-sidebar-border", description: "Sidebar border color" },
      { token: "--sidebar-ring", tailwind: "ring-sidebar-ring", description: "Sidebar focus ring" },
    ],
  },
];

const typeSizes = [
  { label: "text-xs", size: "10px", className: "text-[10px]" },
  { label: "text-sm", size: "12px", className: "text-[12px]" },
  { label: "text-base", size: "14px", className: "text-[14px]" },
  { label: "text-lg", size: "16px", className: "text-[16px]" },
  { label: "text-xl", size: "20px", className: "text-[20px]" },
  { label: "text-2xl", size: "24px", className: "text-[24px]" },
];

const fontWeights = [
  { label: "Normal", weight: 400, className: "font-normal" },
  { label: "Medium", weight: 500, className: "font-medium" },
  { label: "Semibold", weight: 600, className: "font-semibold" },
  { label: "Bold", weight: 700, className: "font-bold" },
];

const spacingScale = [
  { unit: 1, px: 4 },
  { unit: 2, px: 8 },
  { unit: 3, px: 12 },
  { unit: 4, px: 16 },
  { unit: 6, px: 24 },
  { unit: 8, px: 32 },
  { unit: 12, px: 48 },
  { unit: 16, px: 64 },
];

const radii = [
  { label: "rounded-sm", className: "rounded-sm" },
  { label: "rounded", className: "rounded" },
  { label: "rounded-md", className: "rounded-md" },
  { label: "rounded-lg", className: "rounded-lg" },
  { label: "rounded-xl", className: "rounded-xl" },
  { label: "rounded-2xl", className: "rounded-2xl" },
];

const shadows = [
  { label: "shadow-sm", className: "shadow-sm" },
  { label: "shadow", className: "shadow" },
  { label: "shadow-md", className: "shadow-md" },
  { label: "shadow-lg", className: "shadow-lg" },
  { label: "shadow-xl", className: "shadow-xl" },
];

function SectionCard({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="bg-card border border-border rounded-xl p-6">
      <h2 className="text-lg font-semibold text-card-foreground mb-4">
        {title}
      </h2>
      {children}
    </div>
  );
}

function ColorGroupRows({ group }: { group: ColorGroup }) {
  return (
    <>
      <tr>
        <td
          colSpan={5}
          className="pt-4 pb-1 px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground"
        >
          {group.label}
        </td>
      </tr>
      {group.tokens.map((t) => (
        <tr key={t.token} className="border-t border-border/50">
          <td className="px-3 py-2">
            <div
              className="w-8 h-8 rounded-md border border-border"
              style={{ background: `var(${t.token})` }}
            />
          </td>
          <td className="px-3 py-2 font-mono text-xs text-foreground">
            {t.token}
          </td>
          <td className="px-3 py-2 font-mono text-xs text-muted-foreground">
            var({t.token})
          </td>
          <td className="px-3 py-2 font-mono text-xs text-muted-foreground">
            {t.tailwind}
          </td>
          <td className="px-3 py-2 text-sm text-muted-foreground">
            {t.description}
          </td>
        </tr>
      ))}
    </>
  );
}

export function DesignSystemPanel() {
  return (
    <div className="h-full overflow-y-auto p-4 space-y-6 bg-background">
      <h1 className="text-2xl font-bold text-foreground">Design System</h1>

      {/* Color Palette */}
      <SectionCard title="Color Palette">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-border">
                <th className="px-3 py-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                  Swatch
                </th>
                <th className="px-3 py-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                  Token
                </th>
                <th className="px-3 py-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                  CSS Variable
                </th>
                <th className="px-3 py-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                  Tailwind
                </th>
                <th className="px-3 py-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                  Description
                </th>
              </tr>
            </thead>
            <tbody>
              {colorGroups.map((g) => (
                <ColorGroupRows key={g.label} group={g} />
              ))}
            </tbody>
          </table>
        </div>
      </SectionCard>

      {/* Typography */}
      <SectionCard title="Typography">
        <div className="space-y-6">
          <div>
            <h3 className="text-sm font-semibold text-muted-foreground mb-3">
              Font Family: Inter
            </h3>
            <div className="space-y-3">
              {typeSizes.map((s) => (
                <div key={s.label} className="flex items-baseline gap-4">
                  <span className="w-24 shrink-0 font-mono text-xs text-muted-foreground">
                    {s.label} ({s.size})
                  </span>
                  <span
                    className={`${s.className} text-foreground`}
                    style={{ fontFamily: "Inter, sans-serif" }}
                  >
                    The quick brown fox jumps over the lazy dog
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="border-t border-border pt-4">
            <h3 className="text-sm font-semibold text-muted-foreground mb-3">
              Font Weights
            </h3>
            <div className="space-y-2">
              {fontWeights.map((w) => (
                <div key={w.weight} className="flex items-baseline gap-4">
                  <span className="w-24 shrink-0 font-mono text-xs text-muted-foreground">
                    {w.weight}
                  </span>
                  <span
                    className={`text-base text-foreground ${w.className}`}
                    style={{ fontFamily: "Inter, sans-serif" }}
                  >
                    {w.label} &mdash; Trading Dashboard 123,456.78
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="border-t border-border pt-4">
            <h3 className="text-sm font-semibold text-muted-foreground mb-3">
              Monospace: JetBrains Mono
            </h3>
            <div className="space-y-2">
              {typeSizes.slice(0, 4).map((s) => (
                <div key={s.label} className="flex items-baseline gap-4">
                  <span className="w-24 shrink-0 font-mono text-xs text-muted-foreground">
                    {s.label} ({s.size})
                  </span>
                  <span
                    className={`${s.className} text-foreground`}
                    style={{ fontFamily: "'JetBrains Mono', monospace" }}
                  >
                    USD/JPY 149.325 +0.42%
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </SectionCard>

      {/* Spacing Scale */}
      <SectionCard title="Spacing Scale">
        <div className="space-y-3">
          {spacingScale.map((s) => (
            <div key={s.unit} className="flex items-center gap-4">
              <span className="w-20 shrink-0 font-mono text-xs text-muted-foreground text-right">
                {s.unit} ({s.px}px)
              </span>
              <div
                className="bg-primary rounded-sm"
                style={{ width: `${s.px}px`, height: "24px" }}
              />
            </div>
          ))}
        </div>
      </SectionCard>

      {/* Border Radius */}
      <SectionCard title="Border Radius">
        <div className="flex flex-wrap gap-6">
          {radii.map((r) => (
            <div key={r.label} className="flex flex-col items-center gap-2">
              <div
                className={`w-16 h-16 bg-primary ${r.className}`}
              />
              <span className="font-mono text-xs text-muted-foreground">
                {r.label}
              </span>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* Shadows */}
      <SectionCard title="Shadows">
        <div className="flex flex-wrap gap-6">
          {shadows.map((s) => (
            <div key={s.label} className="flex flex-col items-center gap-2">
              <div
                className={`w-24 h-24 bg-card border border-border rounded-lg ${s.className} flex items-center justify-center`}
              >
                <span className="text-xs text-muted-foreground text-center px-1">
                  {s.label}
                </span>
              </div>
            </div>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}

export default DesignSystemPanel;

// marketsui-fi-ng/src/app/components/fi-trading/design-system-panel/design-system-panel.component.ts
import {
  Component,
  ChangeDetectionStrategy,
} from '@angular/core';

interface ColorToken {
  name: string;
  tailwind: string;
  description: string;
}

@Component({
  selector: 'app-design-system-panel',
  standalone: true,
  imports: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="h-full overflow-y-auto p-6 space-y-10">

      <!-- ── Header ──────────────────────────────────────────── -->
      <div>
        <h1 class="text-2xl font-bold text-foreground">Design System</h1>
        <p class="text-sm text-muted-foreground mt-1">
          Tokens, typography, spacing, and visual foundations for the trading UI.
        </p>
      </div>

      <!-- ══════════════════════════════════════════════════════ -->
      <!-- 1. COLOR PALETTE                                      -->
      <!-- ══════════════════════════════════════════════════════ -->
      <section>
        <h2 class="text-lg font-semibold text-foreground mb-4">Color Palette</h2>

        @for (group of colorGroups; track group.label) {
          <h3 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground mt-6 mb-2">
            {{ group.label }}
          </h3>
          <div class="overflow-x-auto">
            <table class="w-full text-xs border-collapse">
              <thead>
                <tr class="border-b border-border text-left text-muted-foreground">
                  <th class="py-2 pr-3 w-12">Swatch</th>
                  <th class="py-2 pr-3">Token</th>
                  <th class="py-2 pr-3">CSS Variable</th>
                  <th class="py-2 pr-3">Tailwind</th>
                  <th class="py-2">Description</th>
                </tr>
              </thead>
              <tbody>
                @for (token of group.tokens; track token.name) {
                  <tr class="border-b border-border/50 hover:bg-muted/30">
                    <td class="py-2 pr-3">
                      <div
                        class="w-8 h-8 rounded-md border border-border"
                        [style.background]="'var(--' + token.name + ')'"
                      ></div>
                    </td>
                    <td class="py-2 pr-3 font-mono text-foreground">--{{ token.name }}</td>
                    <td class="py-2 pr-3 font-mono text-muted-foreground">var(--{{ token.name }})</td>
                    <td class="py-2 pr-3 font-mono text-muted-foreground">{{ token.tailwind }}</td>
                    <td class="py-2 text-muted-foreground">{{ token.description }}</td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      </section>

      <!-- ══════════════════════════════════════════════════════ -->
      <!-- 2. TYPOGRAPHY                                         -->
      <!-- ══════════════════════════════════════════════════════ -->
      <section>
        <h2 class="text-lg font-semibold text-foreground mb-4">Typography</h2>

        <div class="bg-card rounded-xl border border-border p-6 space-y-6">
          <!-- Inter -->
          <div>
            <h3 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">
              Inter &mdash; Primary Font
            </h3>
            <div class="space-y-3">
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-2xl / font-bold (24px / 700)</span>
                <p class="text-2xl font-bold text-foreground">The quick brown fox jumps over the lazy dog</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-xl / font-semibold (20px / 600)</span>
                <p class="text-xl font-semibold text-foreground">The quick brown fox jumps over the lazy dog</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-lg / font-medium (18px / 500)</span>
                <p class="text-lg font-medium text-foreground">The quick brown fox jumps over the lazy dog</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-base / font-normal (16px / 400)</span>
                <p class="text-base font-normal text-foreground">The quick brown fox jumps over the lazy dog</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-sm / font-normal (14px / 400)</span>
                <p class="text-sm font-normal text-foreground">The quick brown fox jumps over the lazy dog</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-xs / font-normal (12px / 400)</span>
                <p class="text-xs font-normal text-foreground">The quick brown fox jumps over the lazy dog</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-[11px] / font-medium (11px / 500)</span>
                <p class="text-[11px] font-medium text-foreground">The quick brown fox jumps over the lazy dog</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-[10px] / font-medium (10px / 500)</span>
                <p class="text-[10px] font-medium text-foreground">THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG</p>
              </div>
            </div>
          </div>

          <div class="h-px bg-border"></div>

          <!-- JetBrains Mono -->
          <div>
            <h3 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">
              JetBrains Mono &mdash; Monospace
            </h3>
            <div class="space-y-3">
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-sm / font-mono (14px)</span>
                <p class="text-sm font-mono text-foreground">UST 10Y 4.285% +2.3bps</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-xs / font-mono (12px)</span>
                <p class="text-xs font-mono text-foreground">DV01: $12,450 | P&amp;L: +$234,567</p>
              </div>
              <div>
                <span class="text-[10px] text-muted-foreground font-mono">text-[11px] / font-mono tabular-nums (11px)</span>
                <p class="text-[11px] font-mono tabular-nums text-foreground">102-16+ / 102-17 &nbsp; 3.2M &nbsp; +0.5</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- ══════════════════════════════════════════════════════ -->
      <!-- 3. SPACING SCALE                                      -->
      <!-- ══════════════════════════════════════════════════════ -->
      <section>
        <h2 class="text-lg font-semibold text-foreground mb-4">Spacing Scale</h2>

        <div class="bg-card rounded-xl border border-border p-6">
          <div class="space-y-3">
            @for (sp of spacingScale; track sp.label) {
              <div class="flex items-center gap-4">
                <span class="text-xs font-mono text-muted-foreground w-10 text-right">{{ sp.label }}</span>
                <span class="text-[10px] font-mono text-muted-foreground w-12">{{ sp.px }}</span>
                <div
                  class="h-4 rounded-sm bg-primary/70"
                  [style.width.px]="sp.pxNum"
                ></div>
              </div>
            }
          </div>
        </div>
      </section>

      <!-- ══════════════════════════════════════════════════════ -->
      <!-- 4. BORDER RADIUS                                      -->
      <!-- ══════════════════════════════════════════════════════ -->
      <section>
        <h2 class="text-lg font-semibold text-foreground mb-4">Border Radius</h2>

        <div class="bg-card rounded-xl border border-border p-6">
          <div class="flex flex-wrap gap-6">
            @for (r of borderRadii; track r.label) {
              <div class="flex flex-col items-center gap-2">
                <div
                  class="w-20 h-20 bg-primary/20 border-2 border-primary"
                  [style.border-radius]="r.value"
                ></div>
                <span class="text-xs font-mono text-foreground">{{ r.label }}</span>
                <span class="text-[10px] text-muted-foreground">{{ r.value }}</span>
              </div>
            }
          </div>
        </div>
      </section>

      <!-- ══════════════════════════════════════════════════════ -->
      <!-- 5. SHADOWS                                            -->
      <!-- ══════════════════════════════════════════════════════ -->
      <section class="pb-10">
        <h2 class="text-lg font-semibold text-foreground mb-4">Shadows</h2>

        <div class="bg-card rounded-xl border border-border p-6">
          <div class="flex flex-wrap gap-8">
            @for (s of shadows; track s.label) {
              <div class="flex flex-col items-center gap-3">
                <div
                  class="w-32 h-24 rounded-lg bg-background border border-border"
                  [class]="s.class"
                ></div>
                <span class="text-xs font-mono text-foreground">{{ s.label }}</span>
                <span class="text-[10px] text-muted-foreground">{{ s.tailwind }}</span>
              </div>
            }
          </div>
        </div>
      </section>

    </div>
  `,
})
export class DesignSystemPanelComponent {

  /* ── Color Tokens ────────────────────────────────────── */
  readonly colorGroups: { label: string; tokens: ColorToken[] }[] = [
    {
      label: 'Core Surfaces',
      tokens: [
        { name: 'background',          tailwind: 'bg-background',          description: 'Page / app background' },
        { name: 'foreground',           tailwind: 'text-foreground',        description: 'Primary text color' },
        { name: 'card',                 tailwind: 'bg-card',                description: 'Card / panel background' },
        { name: 'card-foreground',      tailwind: 'text-card-foreground',   description: 'Text on cards' },
        { name: 'popover',              tailwind: 'bg-popover',             description: 'Popover / dropdown background' },
        { name: 'popover-foreground',   tailwind: 'text-popover-foreground', description: 'Text inside popovers' },
      ],
    },
    {
      label: 'Brand',
      tokens: [
        { name: 'primary',             tailwind: 'bg-primary',             description: 'Primary brand / interactive color' },
        { name: 'primary-foreground',   tailwind: 'text-primary-foreground', description: 'Text on primary backgrounds' },
      ],
    },
    {
      label: 'Neutral',
      tokens: [
        { name: 'secondary',           tailwind: 'bg-secondary',           description: 'Secondary surfaces' },
        { name: 'secondary-foreground', tailwind: 'text-secondary-foreground', description: 'Text on secondary' },
        { name: 'muted',               tailwind: 'bg-muted',               description: 'Muted / subtle backgrounds' },
        { name: 'muted-foreground',     tailwind: 'text-muted-foreground',  description: 'De-emphasized text' },
        { name: 'accent',              tailwind: 'bg-accent',              description: 'Accent highlights' },
        { name: 'accent-foreground',    tailwind: 'text-accent-foreground', description: 'Text on accent' },
      ],
    },
    {
      label: 'Semantic',
      tokens: [
        { name: 'destructive',          tailwind: 'bg-destructive',         description: 'Error / destructive actions' },
        { name: 'destructive-foreground', tailwind: 'text-destructive-foreground', description: 'Text on destructive' },
      ],
    },
    {
      label: 'Chrome',
      tokens: [
        { name: 'border',              tailwind: 'border-border',          description: 'Borders and dividers' },
        { name: 'input',               tailwind: 'border-input',           description: 'Input field borders' },
        { name: 'ring',                tailwind: 'ring-ring',              description: 'Focus ring color' },
      ],
    },
    {
      label: 'Trading: Buy/Sell',
      tokens: [
        { name: 'buy',                 tailwind: 'bg-buy',                 description: 'Buy action background' },
        { name: 'buy-foreground',       tailwind: 'text-buy-foreground',    description: 'Text on buy background' },
        { name: 'sell',                tailwind: 'bg-sell',                description: 'Sell action background' },
        { name: 'sell-foreground',      tailwind: 'text-sell-foreground',   description: 'Text on sell background' },
      ],
    },
    {
      label: 'Trading: P&L',
      tokens: [
        { name: 'positive',            tailwind: 'text-positive',          description: 'Profit / positive change' },
        { name: 'negative',            tailwind: 'text-negative',          description: 'Loss / negative change' },
        { name: 'unchanged',           tailwind: 'text-unchanged',         description: 'Flat / no change' },
      ],
    },
    {
      label: 'Trading: Order Status',
      tokens: [
        { name: 'status-filled',       tailwind: 'text-status-filled',     description: 'Fully filled orders' },
        { name: 'status-partial',       tailwind: 'text-status-partial',    description: 'Partially filled orders' },
        { name: 'status-working',       tailwind: 'text-status-working',    description: 'Working / open orders' },
        { name: 'status-cancelled',     tailwind: 'text-status-cancelled',  description: 'Cancelled orders' },
        { name: 'status-rejected',      tailwind: 'text-status-rejected',   description: 'Rejected orders' },
      ],
    },
    {
      label: 'Alerts',
      tokens: [
        { name: 'warning',             tailwind: 'bg-warning',             description: 'Warning / caution state' },
        { name: 'warning-foreground',   tailwind: 'text-warning-foreground', description: 'Text on warning' },
        { name: 'info',                tailwind: 'bg-info',                description: 'Informational state' },
        { name: 'info-foreground',      tailwind: 'text-info-foreground',   description: 'Text on info' },
        { name: 'success',             tailwind: 'bg-success',             description: 'Success state' },
        { name: 'success-foreground',   tailwind: 'text-success-foreground', description: 'Text on success' },
      ],
    },
    {
      label: 'Charts',
      tokens: [
        { name: 'chart-1',             tailwind: 'bg-chart-1',             description: 'Chart series 1 (blue)' },
        { name: 'chart-2',             tailwind: 'bg-chart-2',             description: 'Chart series 2 (green)' },
        { name: 'chart-3',             tailwind: 'bg-chart-3',             description: 'Chart series 3 (amber)' },
        { name: 'chart-4',             tailwind: 'bg-chart-4',             description: 'Chart series 4 (red)' },
        { name: 'chart-5',             tailwind: 'bg-chart-5',             description: 'Chart series 5 (purple)' },
      ],
    },
    {
      label: 'UI',
      tokens: [
        { name: 'highlight',           tailwind: 'bg-highlight',           description: 'Row hover highlight' },
        { name: 'selection',            tailwind: 'bg-selection',           description: 'Selected row / item' },
        { name: 'ticker-bar',          tailwind: 'bg-ticker-bar',          description: 'Scrolling ticker bar background' },
        { name: 'ticker-bar-foreground', tailwind: 'text-ticker-bar-foreground', description: 'Ticker bar text' },
      ],
    },
    {
      label: 'Sidebar',
      tokens: [
        { name: 'sidebar',                     tailwind: 'bg-sidebar',                     description: 'Sidebar background' },
        { name: 'sidebar-foreground',           tailwind: 'text-sidebar-foreground',        description: 'Sidebar text' },
        { name: 'sidebar-primary',              tailwind: 'bg-sidebar-primary',             description: 'Sidebar primary accent' },
        { name: 'sidebar-primary-foreground',   tailwind: 'text-sidebar-primary-foreground', description: 'Text on sidebar primary' },
        { name: 'sidebar-accent',               tailwind: 'bg-sidebar-accent',              description: 'Sidebar accent background' },
        { name: 'sidebar-accent-foreground',     tailwind: 'text-sidebar-accent-foreground', description: 'Text on sidebar accent' },
        { name: 'sidebar-border',               tailwind: 'border-sidebar-border',          description: 'Sidebar border color' },
        { name: 'sidebar-ring',                 tailwind: 'ring-sidebar-ring',              description: 'Sidebar focus ring' },
      ],
    },
  ];

  /* ── Spacing Scale ───────────────────────────────────── */
  readonly spacingScale = [
    { label: '0.5', px: '2px',  pxNum: 2 },
    { label: '1',   px: '4px',  pxNum: 4 },
    { label: '1.5', px: '6px',  pxNum: 6 },
    { label: '2',   px: '8px',  pxNum: 8 },
    { label: '3',   px: '12px', pxNum: 12 },
    { label: '4',   px: '16px', pxNum: 16 },
    { label: '5',   px: '20px', pxNum: 20 },
    { label: '6',   px: '24px', pxNum: 24 },
    { label: '8',   px: '32px', pxNum: 32 },
    { label: '10',  px: '40px', pxNum: 40 },
    { label: '12',  px: '48px', pxNum: 48 },
    { label: '16',  px: '64px', pxNum: 64 },
    { label: '20',  px: '80px', pxNum: 80 },
    { label: '24',  px: '96px', pxNum: 96 },
  ];

  /* ── Border Radius ───────────────────────────────────── */
  readonly borderRadii = [
    { label: 'none',   value: '0px' },
    { label: 'sm',     value: '2px' },
    { label: 'DEFAULT', value: '4px' },
    { label: 'md',     value: '6px' },
    { label: 'lg',     value: '8px' },
    { label: 'xl',     value: '12px' },
    { label: '2xl',    value: '16px' },
    { label: 'full',   value: '9999px' },
  ];

  /* ── Shadows ─────────────────────────────────────────── */
  readonly shadows = [
    { label: 'shadow-sm',  class: 'shadow-sm',  tailwind: 'shadow-sm' },
    { label: 'shadow',     class: 'shadow',     tailwind: 'shadow' },
    { label: 'shadow-md',  class: 'shadow-md',  tailwind: 'shadow-md' },
    { label: 'shadow-lg',  class: 'shadow-lg',  tailwind: 'shadow-lg' },
    { label: 'shadow-xl',  class: 'shadow-xl',  tailwind: 'shadow-xl' },
    { label: 'shadow-2xl', class: 'shadow-2xl', tailwind: 'shadow-2xl' },
  ];
}
