// marketsui-fi/src/components/trading/fi/DashboardPanel.tsx
import { useMemo } from 'react'
import Highcharts from 'highcharts'
import { HighchartsReact } from 'highcharts-react-official'
import type { LayoutItem } from 'react-grid-layout'
import { useMarketData } from './MarketDataContext'
import { PanelGrid, DragHandle } from './PanelGrid'
import { DASHBOARD_ORDERS, DASHBOARD_POSITIONS } from './marketData'
import { cn, fmtYield, fmtBps, fmtPnL, fmtDV01 } from '@/lib/utils'

/* ── KPI data ─────────────────────────────────────────────── */
const KPI_DATA = [
  { label: 'P&L Today', value: 93_170, subtitle: 'Realized + Unrealized', format: 'pnl' },
  { label: 'P&L MTD', value: 243_135, subtitle: 'Month to date', format: 'pnl' },
  { label: 'P&L YTD', value: 590_320, subtitle: 'Year to date', format: 'pnl' },
  { label: 'Net DV01', value: 420_945, subtitle: 'Rate sensitivity', format: 'dv01' },
  { label: 'Net CS01', value: 57_182, subtitle: 'Credit sensitivity', format: 'dv01' },
] as const

function formatKpi(value: number, format: string) {
  if (format === 'pnl') return fmtPnL(value)
  return fmtDV01(value)
}

/* ── Panel card wrapper ───────────────────────────────────── */
function PanelCard({
  title,
  children,
  className,
}: {
  title: string
  children: React.ReactNode
  className?: string
}) {
  return (
    <div
      className={cn(
        'relative bg-card border border-border rounded-xl h-full flex flex-col overflow-hidden',
        className
      )}
    >
      <div className="flex items-center justify-between px-4 pt-3 pb-2">
        <h3 className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
          {title}
        </h3>
        <DragHandle />
      </div>
      <div className="flex-1 min-h-0 overflow-auto px-4 pb-3">{children}</div>
    </div>
  )
}

/* ── KPI Card ─────────────────────────────────────────────── */
function KpiCard({
  label,
  value,
  subtitle,
  format,
}: {
  label: string
  value: number
  subtitle: string
  format: string
}) {
  const isPnl = format === 'pnl'
  const isPositive = value >= 0

  return (
    <div className="relative bg-card border border-border rounded-xl p-4 flex flex-col justify-between h-full overflow-hidden">
      <DragHandle />
      <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        {label}
      </span>
      <span
        className={cn(
          'text-xl font-mono font-semibold mt-1',
          isPnl && isPositive && 'text-buy',
          isPnl && !isPositive && 'text-sell',
          !isPnl && 'text-foreground'
        )}
      >
        {formatKpi(value, format)}
      </span>
      <span className="text-[10px] text-muted-foreground mt-0.5">{subtitle}</span>
    </div>
  )
}


/* ── Status badge ─────────────────────────────────────────── */
function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    Filled: 'bg-buy/15 text-buy',
    Working: 'bg-primary/15 text-primary',
    Partial: 'bg-warning/15 text-warning',
    Cancelled: 'bg-muted text-muted-foreground',
  }

  return (
    <span
      className={cn(
        'inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-medium',
        styles[status] ?? 'bg-muted text-muted-foreground'
      )}
    >
      {status}
    </span>
  )
}

/* ── Layouts ──────────────────────────────────────────────── */
const LAYOUTS: Record<string, LayoutItem[]> = {
  lg: [
    // KPI row – 5 cards across 12 cols
    { i: 'kpi-0', x: 0, y: 0, w: 2, h: 4 },
    { i: 'kpi-1', x: 2, y: 0, w: 3, h: 4 },
    { i: 'kpi-2', x: 5, y: 0, w: 2, h: 4 },
    { i: 'kpi-3', x: 7, y: 0, w: 3, h: 4 },
    { i: 'kpi-4', x: 10, y: 0, w: 2, h: 4 },
    // Second row
    { i: 'yield-curve', x: 0, y: 4, w: 5, h: 10 },
    { i: 'benchmarks', x: 5, y: 4, w: 3, h: 10 },
    { i: 'positions', x: 8, y: 4, w: 4, h: 10 },
    // Third row
    { i: 'recent-orders', x: 0, y: 14, w: 12, h: 9 },
  ],
  md: [
    { i: 'kpi-0', x: 0, y: 0, w: 2, h: 4 },
    { i: 'kpi-1', x: 2, y: 0, w: 3, h: 4 },
    { i: 'kpi-2', x: 5, y: 0, w: 2, h: 4 },
    { i: 'kpi-3', x: 7, y: 0, w: 3, h: 4 },
    { i: 'kpi-4', x: 10, y: 0, w: 2, h: 4 },
    { i: 'yield-curve', x: 0, y: 4, w: 6, h: 10 },
    { i: 'benchmarks', x: 6, y: 4, w: 6, h: 10 },
    { i: 'positions', x: 0, y: 14, w: 6, h: 10 },
    { i: 'recent-orders', x: 6, y: 14, w: 6, h: 10 },
  ],
  sm: [
    { i: 'kpi-0', x: 0, y: 0, w: 3, h: 4 },
    { i: 'kpi-1', x: 3, y: 0, w: 3, h: 4 },
    { i: 'kpi-2', x: 0, y: 4, w: 3, h: 4 },
    { i: 'kpi-3', x: 3, y: 4, w: 3, h: 4 },
    { i: 'kpi-4', x: 0, y: 8, w: 6, h: 4 },
    { i: 'yield-curve', x: 0, y: 12, w: 6, h: 10 },
    { i: 'benchmarks', x: 0, y: 22, w: 6, h: 10 },
    { i: 'positions', x: 0, y: 32, w: 6, h: 10 },
    { i: 'recent-orders', x: 0, y: 42, w: 6, h: 10 },
  ],
}

/* ── Main Dashboard Panel ─────────────────────────────────── */
export function DashboardPanel() {
  const marketData = useMarketData()
  const { treasuries, yieldCurve, cdxIndices } = marketData

  /* Key benchmarks */
  const ust2 = treasuries.find((t) => t.tenor === '2Y')
  const ust10 = treasuries.find((t) => t.tenor === '10Y')
  const ust30 = treasuries.find((t) => t.tenor === '30Y')
  const cdxIG = cdxIndices.find((c) => c.name.includes('IG'))
  const cdxHY = cdxIndices.find((c) => c.name.includes('HY'))
  const slope2s10s = ust10 && ust2 ? (ust10.mid - ust2.mid) * 100 : 0

  const benchmarks = useMemo(
    () => [
      { name: '2Y UST', value: ust2?.mid, chg: ust2?.chg, isYield: true },
      { name: '10Y UST', value: ust10?.mid, chg: ust10?.chg, isYield: true },
      { name: '30Y UST', value: ust30?.mid, chg: ust30?.chg, isYield: true },
      { name: 'CDX IG', value: cdxIG?.mid, chg: cdxIG?.chg, isYield: false },
      { name: 'CDX HY', value: cdxHY?.mid, chg: cdxHY?.chg, isYield: false },
      { name: '2s10s Slope', value: slope2s10s, chg: undefined, isYield: false },
    ],
    [ust2, ust10, ust30, cdxIG, cdxHY, slope2s10s]
  )

  /* Yield curve Highcharts options */
  const yieldCurveOptions = useMemo<Highcharts.Options>(
    () => ({
      chart: { backgroundColor: 'transparent', style: { fontFamily: "'Inter', sans-serif" }, height: null as unknown as number },
      credits: { enabled: false },
      title: { text: undefined },
      xAxis: {
        categories: yieldCurve.map((pt) => pt.tenor),
        labels: { style: { color: '#9DA0A5', fontSize: '10px' } },
        lineColor: '#2C2F33',
        tickLength: 0,
      },
      yAxis: {
        title: { text: undefined },
        labels: { format: '{value:.1f}%', style: { color: '#9DA0A5', fontSize: '10px' } },
        gridLineColor: '#2C2F33',
        lineWidth: 0,
      },
      legend: { enabled: false },
      tooltip: {
        backgroundColor: '#1A1D21',
        borderColor: '#2C2F33',
        borderRadius: 8,
        style: { color: '#FFFFFF', fontSize: '11px', fontFamily: "'Inter', sans-serif" },
        formatter: function (this: Highcharts.TooltipFormatterContextObject) {
          const pts = this.points ?? [this]
          let s = `<span style="color:#9DA0A5;font-size:10px">${this.x}</span><br/>`
          for (const p of pts) {
            const label = p.series.name === 'today' ? 'Today' : 'Prev Close'
            s += `<span>${label}: ${Number(p.y).toFixed(3)}%</span><br/>`
          }
          return s
        },
        shared: true,
        useHTML: true,
      },
      plotOptions: {
        series: { animation: false, marker: { enabled: false } },
      },
      series: [
        {
          name: 'today',
          type: 'areaspline',
          data: yieldCurve.map((pt) => pt.yield),
          color: '#60A5FA',
          lineWidth: 2,
          fillColor: {
            linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
            stops: [[0, 'rgba(45,212,191,0.15)'], [1, 'rgba(45,212,191,0)']],
          },
        },
        {
          name: 'prevClose',
          type: 'spline',
          data: yieldCurve.map((pt) => pt.prevClose),
          color: '#9DA0A5',
          lineWidth: 1.5,
          dashStyle: 'ShortDash',
        },
      ],
    }),
    [yieldCurve]
  )

  const recentOrders = DASHBOARD_ORDERS.slice(0, 6)
  const positions = DASHBOARD_POSITIONS.slice(0, 8)

  return (
    <PanelGrid layouts={LAYOUTS} rowHeight={30}>
      {/* ── KPI Cards ──────────────────────────────────────── */}
      {KPI_DATA.map((kpi, i) => (
        <div key={`kpi-${i}`}>
          <KpiCard
            label={kpi.label}
            value={kpi.value}
            subtitle={kpi.subtitle}
            format={kpi.format}
          />
        </div>
      ))}

      {/* ── Yield Curve ────────────────────────────────────── */}
      <div key="yield-curve">
        <PanelCard title="Yield Curve">
          <div style={{ width: '100%', height: '100%' }}>
            <HighchartsReact highcharts={Highcharts} options={yieldCurveOptions} containerProps={{ style: { width: '100%', height: '100%' } }} />
          </div>
        </PanelCard>
      </div>

      {/* ── Key Benchmarks ─────────────────────────────────── */}
      <div key="benchmarks">
        <PanelCard title="Key Benchmarks">
          <div className="flex flex-col gap-1">
            {benchmarks.map((b) => (
              <div
                key={b.name}
                className="flex items-center justify-between py-2 border-b border-border/50 last:border-b-0"
              >
                <span className="text-xs text-muted-foreground">{b.name}</span>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono text-foreground">
                    {b.value != null
                      ? b.isYield
                        ? fmtYield(b.value)
                        : b.name === '2s10s Slope'
                          ? b.value.toFixed(1) + ' bps'
                          : b.value.toFixed(1)
                      : '—'}
                  </span>
                  {b.chg != null && (
                    <span
                      className={cn(
                        'text-[10px] font-mono',
                        b.chg >= 0 ? 'text-sell' : 'text-buy'
                      )}
                    >
                      {fmtBps(b.chg)}
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </PanelCard>
      </div>

      {/* ── Position Summary ───────────────────────────────── */}
      <div key="positions">
        <PanelCard title="Position Summary">
          <div className="flex flex-col gap-0.5">
            {positions.map((pos, i) => (
              <div
                key={i}
                className="flex items-center justify-between py-1.5 border-b border-border/50 last:border-b-0"
              >
                <div className="flex items-center gap-2 min-w-0">
                  <span
                    className={cn(
                      'text-[10px] font-mono w-4 text-center',
                      pos.direction === 'Long' ? 'text-buy' : 'text-sell'
                    )}
                  >
                    {pos.direction === 'Long' ? '\u2191' : '\u2193'}
                  </span>
                  <span className="text-xs text-foreground truncate">{pos.security}</span>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  <span
                    className={cn(
                      'text-xs font-mono',
                      pos.pnl >= 0 ? 'text-buy' : 'text-sell'
                    )}
                  >
                    {fmtPnL(pos.pnl)}
                  </span>
                  <span className="text-[10px] font-mono text-muted-foreground">
                    {fmtDV01(pos.dv01)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </PanelCard>
      </div>

      {/* ── Recent Orders ──────────────────────────────────── */}
      <div key="recent-orders">
        <PanelCard title="Recent Orders">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-border">
                <th className="text-left py-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Time
                </th>
                <th className="text-left py-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Security
                </th>
                <th className="text-left py-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Side
                </th>
                <th className="text-right py-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Size
                </th>
                <th className="text-right py-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Yield / Price
                </th>
                <th className="text-right py-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Status
                </th>
              </tr>
            </thead>
            <tbody>
              {recentOrders.map((order, i) => (
                <tr
                  key={i}
                  className="border-b border-border/50 last:border-b-0 hover:bg-secondary/40 transition-colors"
                >
                  <td className="py-2 font-mono text-muted-foreground">{order.time}</td>
                  <td className="py-2 text-foreground">{order.security}</td>
                  <td className="py-2">
                    <span className={cn(order.side === 'Buy' ? 'text-buy' : 'text-sell')}>
                      {order.side}
                    </span>
                  </td>
                  <td className="py-2 text-right font-mono text-foreground">{order.size}</td>
                  <td className="py-2 text-right font-mono text-foreground">{order.yieldPrice}</td>
                  <td className="py-2 text-right">
                    <StatusBadge status={order.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </PanelCard>
      </div>
    </PanelGrid>
  )
}

export default DashboardPanel

// marketsui-fi-ng/src/app/components/fi-trading/dashboard-panel/dashboard-panel.component.ts
import {
  Component,
  inject,
  computed,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { HighchartsChartComponent } from 'highcharts-angular';
import type { Options, AxisLabelsFormatterContextObject } from 'highcharts';
import { MarketDataService } from '../../../services/market-data.service';
import { fmtYield, fmtBps, fmtPnL, fmtDV01 } from '../../../shared/utils';

interface KpiCard {
  label: string;
  value: string;
  color: 'pnl' | 'neutral';
  raw: number;
}

@Component({
  selector: 'app-dashboard-panel',
  standalone: true,
  imports: [CommonModule, HighchartsChartComponent],
  template: `
    <!-- ── Dashboard Grid ────────────────────────────────── -->
    <div class="grid grid-cols-12 gap-3 p-4 h-full overflow-y-auto">

      <!-- ── KPI Row ─────────────────────────────────────── -->
      <div class="col-span-12 grid grid-cols-5 gap-3">
        @for (kpi of kpis; track kpi.label) {
          <div class="bg-card rounded-lg border border-border px-4 py-3 flex flex-col gap-0.5">
            <span class="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
              {{ kpi.label }}
            </span>
            <span
              class="text-lg font-semibold font-mono tabular-nums"
              [class.text-buy]="kpi.color === 'pnl' && kpi.raw >= 0"
              [class.text-sell]="kpi.color === 'pnl' && kpi.raw < 0"
              [class.text-foreground]="kpi.color === 'neutral'"
            >
              {{ kpi.value }}
            </span>
          </div>
        }
      </div>

      <!-- ── Yield Curve Chart ───────────────────────────── -->
      <div class="col-span-5 bg-card rounded-lg border border-border p-4 flex flex-col">
        <h3 class="text-xs font-semibold text-foreground mb-1">UST Yield Curve</h3>
        <div class="flex items-center gap-3 mb-2">
          <span class="flex items-center gap-1 text-[10px] text-muted-foreground">
            <span class="inline-block w-3 h-0.5 rounded-full bg-primary"></span> Today
          </span>
          <span class="flex items-center gap-1 text-[10px] text-muted-foreground">
            <span class="inline-block w-3 h-0.5 rounded-full bg-muted-foreground opacity-50 border-dashed"></span> Prev Close
          </span>
        </div>
        <div class="flex-1 min-h-0 relative">
          <highcharts-chart
            [options]="yieldCurveOptions()"
            style="width:100%;height:100%;display:block;"
          />
        </div>
      </div>

      <!-- ── Key Benchmarks ──────────────────────────────── -->
      <div class="col-span-3 bg-card rounded-lg border border-border p-4 flex flex-col">
        <h3 class="text-xs font-semibold text-foreground mb-3">Key Benchmarks</h3>
        <div class="flex flex-col gap-2 flex-1">
          @for (bm of mds.benchmarks(); track bm.label) {
            <div class="flex items-center justify-between py-1 border-b border-border last:border-b-0">
              <span class="text-[11px] text-muted-foreground font-medium">{{ bm.label }}</span>
              <div class="flex items-center gap-2">
                <span class="text-[11px] font-mono font-semibold text-foreground tabular-nums">
                  {{ formatBenchmarkValue(bm) }}
                </span>
                <span
                  class="text-[10px] font-mono tabular-nums"
                  [class.text-buy]="bm.change < 0"
                  [class.text-sell]="bm.change > 0"
                  [class.text-muted-foreground]="bm.change === 0"
                >
                  {{ formatBps(bm.change) }}
                </span>
              </div>
            </div>
          }
        </div>
      </div>

      <!-- ── Position Summary ────────────────────────────── -->
      <div class="col-span-4 bg-card rounded-lg border border-border p-4 flex flex-col">
        <h3 class="text-xs font-semibold text-foreground mb-3">Position Summary</h3>
        <div class="flex flex-col gap-1.5 flex-1 overflow-y-auto">
          @for (pos of mds.dashboardPositions(); track pos.security) {
            <div class="flex items-center gap-2 py-1.5 px-2 rounded-md hover:bg-secondary/50 transition-colors">
              <span
                class="text-xs"
                [class.text-buy]="pos.side === 'LONG'"
                [class.text-sell]="pos.side === 'SHORT'"
              >
                {{ pos.side === 'LONG' ? '\u25B2' : '\u25BC' }}
              </span>
              <span class="text-[11px] font-medium text-foreground flex-1 truncate">
                {{ pos.security }}
              </span>
              <span
                class="text-[11px] font-mono tabular-nums min-w-[68px] text-right"
                [class.text-buy]="pos.pnlToday >= 0"
                [class.text-sell]="pos.pnlToday < 0"
              >
                {{ formatPnL(pos.pnlToday) }}
              </span>
              <span class="text-[10px] font-mono tabular-nums text-muted-foreground min-w-[58px] text-right">
                {{ formatDV01(pos.dv01) }}
              </span>
            </div>
          }
        </div>
      </div>

      <!-- ── Recent Orders ───────────────────────────────── -->
      <div class="col-span-12 bg-card rounded-lg border border-border p-4 flex flex-col">
        <h3 class="text-xs font-semibold text-foreground mb-3">Recent Orders</h3>
        <div class="overflow-x-auto">
          <table class="w-full text-[11px]">
            <thead>
              <tr class="border-b border-border">
                <th class="text-left py-1.5 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Time</th>
                <th class="text-left py-1.5 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Security</th>
                <th class="text-left py-1.5 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Side</th>
                <th class="text-right py-1.5 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Size (MM)</th>
                <th class="text-right py-1.5 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Yield</th>
                <th class="text-right py-1.5 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Price</th>
                <th class="text-center py-1.5 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Status</th>
              </tr>
            </thead>
            <tbody>
              @for (order of mds.recentOrders(); track order.orderId) {
                <tr class="border-b border-border last:border-b-0 hover:bg-secondary/30 transition-colors">
                  <td class="py-2 px-2 font-mono tabular-nums text-muted-foreground">{{ order.time }}</td>
                  <td class="py-2 px-2 font-medium text-foreground">{{ order.security }}</td>
                  <td class="py-2 px-2">
                    <span
                      class="font-semibold"
                      [class.text-buy]="order.side === 'BUY'"
                      [class.text-sell]="order.side === 'SELL'"
                    >
                      {{ order.side }}
                    </span>
                  </td>
                  <td class="py-2 px-2 text-right font-mono tabular-nums text-foreground">{{ order.sizeMM }}</td>
                  <td class="py-2 px-2 text-right font-mono tabular-nums text-foreground">
                    {{ order.status === 'Filled' || order.status === 'Partial'
                        ? formatYield(order.avgYield)
                        : formatYield(order.lmtYield) }}
                  </td>
                  <td class="py-2 px-2 text-right font-mono tabular-nums text-foreground">
                    {{ order.status === 'Filled' || order.status === 'Partial'
                        ? order.avgPrice.toFixed(3)
                        : order.lmtPrice.toFixed(3) }}
                  </td>
                  <td class="py-2 px-2 text-center">
                    <span
                      class="inline-block rounded-full px-2 py-0.5 text-[10px] font-medium"
                      [ngClass]="statusClass(order.status)"
                    >
                      {{ order.status }}
                    </span>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      </div>

    </div>
  `,
  styles: [`
    :host {
      display: block;
      height: 100%;
      overflow: hidden;
    }
  `],
})
export class DashboardPanelComponent {
  protected readonly mds = inject(MarketDataService);

  /* ── KPI Data ──────────────────────────────────────────── */
  readonly kpis: KpiCard[] = [
    { label: 'P&L Today', value: fmtPnL(93170), color: 'pnl', raw: 93170 },
    { label: 'P&L MTD', value: fmtPnL(243135), color: 'pnl', raw: 243135 },
    { label: 'P&L YTD', value: fmtPnL(590320), color: 'pnl', raw: 590320 },
    { label: 'Net DV01', value: fmtDV01(420945), color: 'neutral', raw: 420945 },
    { label: 'Net CS01', value: fmtDV01(57182), color: 'neutral', raw: 57182 },
  ];

  /* ── Format helpers ────────────────────────────────────── */
  formatYield = fmtYield;
  formatBps = fmtBps;
  formatPnL = fmtPnL;
  formatDV01 = fmtDV01;

  formatBenchmarkValue(bm: { value: number; unit: string }): string {
    if (bm.unit === 'yield') return fmtYield(bm.value);
    return bm.value.toFixed(1);
  }

  statusClass(status: string): Record<string, boolean> {
    return {
      'bg-buy/15 text-buy': status === 'Filled',
      'bg-primary/15 text-primary': status === 'Working',
      'bg-warning/15 text-warning': status === 'Partial',
      'bg-muted text-muted-foreground': status === 'Cancelled',
    };
  }

  /* ── Highcharts yield curve options (reactive) ──────────── */
  readonly yieldCurveOptions = computed((): Options => {
    const data = this.mds.yieldCurve();
    const categories = data.map((p) => p.tenor);
    const todayValues = data.map((p) => p.yield);
    const prevValues = data.map((p) => p.prevClose);

    const style = getComputedStyle(document.documentElement);
    const primaryColor = style.getPropertyValue('--primary').trim() || '#60A5FA';
    const mutedFg = style.getPropertyValue('--muted-foreground').trim() || '#9DA0A5';
    const borderColor = style.getPropertyValue('--border').trim() || '#2C2F33';

    return {
      chart: { backgroundColor: 'transparent', style: { fontFamily: "'Inter', sans-serif" } },
      credits: { enabled: false },
      title: { text: undefined },
      legend: { enabled: false },
      xAxis: {
        categories,
        lineColor: borderColor,
        tickColor: borderColor,
        labels: { style: { color: mutedFg, fontSize: '10px' } },
        gridLineColor: borderColor,
        gridLineWidth: 0.5,
      },
      yAxis: {
        title: { text: undefined },
        gridLineColor: borderColor,
        gridLineWidth: 0.5,
        labels: {
          style: { color: mutedFg, fontSize: '10px' },
          formatter(this: AxisLabelsFormatterContextObject): string {
            return (typeof this.value === 'number' ? this.value.toFixed(1) + '%' : String(this.value));
          },
        },
      },
      tooltip: {
        shared: true,
        backgroundColor: 'rgba(26, 29, 33, 0.95)',
        borderColor: borderColor,
        style: { color: '#FFFFFF', fontSize: '11px' },
        formatter(): string {
          const self = this as any;
          let s = `<b>${self.x}</b><br/>`;
          (self.points ?? []).forEach((p: any) => {
            s += `<span style="color:${p.color}">\u25CF</span> ${p.series.name}: ${fmtYield(p.y ?? 0)}<br/>`;
          });
          return s;
        },
      },
      plotOptions: {
        area: {
          marker: { radius: 3, lineWidth: 0 },
        },
        series: {
          animation: false,
        },
      },
      series: [
        {
          type: 'area',
          name: 'Today',
          data: todayValues,
          color: primaryColor,
          fillColor: {
            linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
            stops: [
              [0, 'rgba(96, 165, 250, 0.25)'],
              [1, 'rgba(96, 165, 250, 0.02)'],
            ],
          },
          lineWidth: 2,
          marker: { fillColor: primaryColor, lineColor: primaryColor },
        },
        {
          type: 'line',
          name: 'Prev Close',
          data: prevValues,
          color: mutedFg,
          dashStyle: 'ShortDash',
          lineWidth: 1.5,
          marker: { enabled: false },
        },
      ],
    };
  });
}
